version: "1"
services:
  backend:
    image: thiagoproch/desafio-dev-dock
    container_name: backend
    environment:
      POSTGRES_DB: desafio-dev
      POSTGRES_DESAFIO_USERNAME: "${POSTGRES_DESAFIO_USERNAME}"
      POSTGRES_DESAFIO_PASSWORD: "${POSTGRES_DESAFIO_PASSWORD}"
      POSTGRES_URL: "${POSTGRES_URL}"
    ports:
      - "9090:9090"
    depends_on:
      - "db"
  db:
    image: postgres:13.4
    container_name: db
    environment:
      POSTGRES_DB: desafio-dev
      POSTGRES_USER: "${POSTGRES_DESAFIO_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_DESAFIO_PASSWORD}"
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    expose:
      - 5432
volumes:
  db-data: