base.package:
   br.com.desafio
server:
   port: ${DOCK_PORT}
   
spring:
   main:
      sources: br.com.desafio
   datasource:
      url: ${POSTGRES_URL}
      username: ${POSTGRES_DESAFIO_USERNAME}
      password: ${POSTGRES_DESAFIO_PASSWORD}
   jpa:
      hibernate:
         naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl